services:
  db:
    image: postgres:16
    container_name: library_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: library_api
    depends_on:
      - db
    ports:
      - "${API_PORT}:8080"
    environment:
      DB_HOST: ${PGHOST}
      DB_USER: ${PGUSER}
      DB_PASSWORD: ${PGPASSWORD}
      DB_NAME: ${PGDATABASE}
      DB_PORT: ${PGPORT}
    restart: on-failure

volumes:
  db_data:
